/*
 * GENERATED by scripts/sync-icons.mjs. Do not edit by hand.
 */

/*
 * Tabler exposes its per-icon subpaths through an exports map and no real
 * directory. Metro resolves it (unstable_enablePackageExports is on), so does
 * Jest, and types come from types/tabler-icons.d.ts -- only eslint-plugin-import's
 * resolver reads package.json "exports", which it does not.
 */
/* eslint-disable import/no-unresolved */
import type { Icon } from '@tabler/icons-react-native';

import IconAirConditioning from '@tabler/icons-react-native/IconAirConditioning';
import IconWind from '@tabler/icons-react-native/IconWind';
import IconSnowflake from '@tabler/icons-react-native/IconSnowflake';
import IconTemperature from '@tabler/icons-react-native/IconTemperature';
import IconDroplet from '@tabler/icons-react-native/IconDroplet';
import IconDroplets from '@tabler/icons-react-native/IconDroplets';
import IconBath from '@tabler/icons-react-native/IconBath';
import IconToiletPaper from '@tabler/icons-react-native/IconToiletPaper';
import IconPipeline from '@tabler/icons-react-native/IconPipeline';
import IconPool from '@tabler/icons-react-native/IconPool';
import IconTank from '@tabler/icons-react-native/IconTank';
import IconBolt from '@tabler/icons-react-native/IconBolt';
import IconPlug from '@tabler/icons-react-native/IconPlug';
import IconBulb from '@tabler/icons-react-native/IconBulb';
import IconBattery from '@tabler/icons-react-native/IconBattery';
import IconSolarPanel from '@tabler/icons-react-native/IconSolarPanel';
import IconSunElectricity from '@tabler/icons-react-native/IconSunElectricity';
import IconCircuitResistor from '@tabler/icons-react-native/IconCircuitResistor';
import IconAlarm from '@tabler/icons-react-native/IconAlarm';
import IconFireExtinguisher from '@tabler/icons-react-native/IconFireExtinguisher';
import IconWashMachine from '@tabler/icons-react-native/IconWashMachine';
import IconWash from '@tabler/icons-react-native/IconWash';
import IconFridge from '@tabler/icons-react-native/IconFridge';
import IconMicrowave from '@tabler/icons-react-native/IconMicrowave';
import IconBlender from '@tabler/icons-react-native/IconBlender';
import IconGrill from '@tabler/icons-react-native/IconGrill';
import IconVacuumCleaner from '@tabler/icons-react-native/IconVacuumCleaner';
import IconIroning from '@tabler/icons-react-native/IconIroning';
import IconCooker from '@tabler/icons-react-native/IconCooker';
import IconDeviceTv from '@tabler/icons-react-native/IconDeviceTv';
import IconSpray from '@tabler/icons-react-native/IconSpray';
import IconBucket from '@tabler/icons-react-native/IconBucket';
import IconTrash from '@tabler/icons-react-native/IconTrash';
import IconHandSanitizer from '@tabler/icons-react-native/IconHandSanitizer';
import IconWashDryclean from '@tabler/icons-react-native/IconWashDryclean';
import IconBug from '@tabler/icons-react-native/IconBug';
import IconSpider from '@tabler/icons-react-native/IconSpider';
import IconTools from '@tabler/icons-react-native/IconTools';
import IconTool from '@tabler/icons-react-native/IconTool';
import IconHammer from '@tabler/icons-react-native/IconHammer';
import IconHammerDrill from '@tabler/icons-react-native/IconHammerDrill';
import IconRulerMeasure from '@tabler/icons-react-native/IconRulerMeasure';
import IconLadder from '@tabler/icons-react-native/IconLadder';
import IconCrane from '@tabler/icons-react-native/IconCrane';
import IconWall from '@tabler/icons-react-native/IconWall';
import IconStairs from '@tabler/icons-react-native/IconStairs';
import IconDoor from '@tabler/icons-react-native/IconDoor';
import IconWindow from '@tabler/icons-react-native/IconWindow';
import IconFence from '@tabler/icons-react-native/IconFence';
import IconElevator from '@tabler/icons-react-native/IconElevator';
import IconBuilding from '@tabler/icons-react-native/IconBuilding';
import IconBuildingWarehouse from '@tabler/icons-react-native/IconBuildingWarehouse';
import IconBrush from '@tabler/icons-react-native/IconBrush';
import IconPaint from '@tabler/icons-react-native/IconPaint';
import IconPaintFilled from '@tabler/icons-react-native/IconPaintFilled';
import IconPlant from '@tabler/icons-react-native/IconPlant';
import IconPlant2 from '@tabler/icons-react-native/IconPlant2';
import IconTree from '@tabler/icons-react-native/IconTree';
import IconTrees from '@tabler/icons-react-native/IconTrees';
import IconFlower from '@tabler/icons-react-native/IconFlower';
import IconShovel from '@tabler/icons-react-native/IconShovel';
import IconGardenCart from '@tabler/icons-react-native/IconGardenCart';
import IconLawnMower from '@tabler/icons-react-native/IconLawnMower';
import IconHome from '@tabler/icons-react-native/IconHome';
import IconHome2 from '@tabler/icons-react-native/IconHome2';
import IconArmchair from '@tabler/icons-react-native/IconArmchair';
import IconSofa from '@tabler/icons-react-native/IconSofa';
import IconBed from '@tabler/icons-react-native/IconBed';
import IconBlind from '@tabler/icons-react-native/IconBlind';
import IconCar from '@tabler/icons-react-native/IconCar';
import IconCarCrane from '@tabler/icons-react-native/IconCarCrane';
import IconSteeringWheel from '@tabler/icons-react-native/IconSteeringWheel';
import IconTruck from '@tabler/icons-react-native/IconTruck';
import IconTruckDelivery from '@tabler/icons-react-native/IconTruckDelivery';
import IconMotorbike from '@tabler/icons-react-native/IconMotorbike';
import IconBike from '@tabler/icons-react-native/IconBike';
import IconEngine from '@tabler/icons-react-native/IconEngine';
import IconGasStation from '@tabler/icons-react-native/IconGasStation';
import IconWifi from '@tabler/icons-react-native/IconWifi';
import IconRouter from '@tabler/icons-react-native/IconRouter';
import IconNetwork from '@tabler/icons-react-native/IconNetwork';
import IconServer from '@tabler/icons-react-native/IconServer';
import IconDeviceLaptop from '@tabler/icons-react-native/IconDeviceLaptop';
import IconDeviceDesktop from '@tabler/icons-react-native/IconDeviceDesktop';
import IconDeviceMobile from '@tabler/icons-react-native/IconDeviceMobile';
import IconAntenna from '@tabler/icons-react-native/IconAntenna';
import IconSatellite from '@tabler/icons-react-native/IconSatellite';
import IconDeviceCctv from '@tabler/icons-react-native/IconDeviceCctv';
import IconCamera from '@tabler/icons-react-native/IconCamera';
import IconLock from '@tabler/icons-react-native/IconLock';
import IconKey from '@tabler/icons-react-native/IconKey';
import IconShieldLock from '@tabler/icons-react-native/IconShieldLock';
import IconScissors from '@tabler/icons-react-native/IconScissors';
import IconShirt from '@tabler/icons-react-native/IconShirt';
import IconHanger from '@tabler/icons-react-native/IconHanger';
import IconMassage from '@tabler/icons-react-native/IconMassage';
import IconYoga from '@tabler/icons-react-native/IconYoga';
import IconHeartbeat from '@tabler/icons-react-native/IconHeartbeat';
import IconStethoscope from '@tabler/icons-react-native/IconStethoscope';
import IconFirstAidKit from '@tabler/icons-react-native/IconFirstAidKit';
import IconDog from '@tabler/icons-react-native/IconDog';
import IconCat from '@tabler/icons-react-native/IconCat';
import IconPaw from '@tabler/icons-react-native/IconPaw';
import IconBabyCarriage from '@tabler/icons-react-native/IconBabyCarriage';
import IconChefHat from '@tabler/icons-react-native/IconChefHat';
import IconToolsKitchen from '@tabler/icons-react-native/IconToolsKitchen';
import IconToolsKitchen2 from '@tabler/icons-react-native/IconToolsKitchen2';
import IconCake from '@tabler/icons-react-native/IconCake';
import IconCoffee from '@tabler/icons-react-native/IconCoffee';
import IconConfetti from '@tabler/icons-react-native/IconConfetti';
import IconMusic from '@tabler/icons-react-native/IconMusic';
import IconMicrophone from '@tabler/icons-react-native/IconMicrophone';
import IconPhoto from '@tabler/icons-react-native/IconPhoto';
import IconVideo from '@tabler/icons-react-native/IconVideo';
import IconSchool from '@tabler/icons-react-native/IconSchool';
import IconBook from '@tabler/icons-react-native/IconBook';
import IconPackage from '@tabler/icons-react-native/IconPackage';
import IconWindmill from '@tabler/icons-react-native/IconWindmill';
import IconSettings from '@tabler/icons-react-native/IconSettings';
import IconCategory from '@tabler/icons-react-native/IconCategory';

/**
 * Every glyph a trade may be drawn with, keyed by what the server stores.
 *
 * Imported one file at a time and never off the barrel: Metro does not shake,
 * and the barrel carries all 6184.
 */
export const ICONS: Record<string, Icon> = {
    'air-conditioning': IconAirConditioning,
    'wind': IconWind,
    'snowflake': IconSnowflake,
    'temperature': IconTemperature,
    'droplet': IconDroplet,
    'droplets': IconDroplets,
    'bath': IconBath,
    'toilet-paper': IconToiletPaper,
    'pipeline': IconPipeline,
    'pool': IconPool,
    'tank': IconTank,
    'bolt': IconBolt,
    'plug': IconPlug,
    'bulb': IconBulb,
    'battery': IconBattery,
    'solar-panel': IconSolarPanel,
    'sun-electricity': IconSunElectricity,
    'circuit-resistor': IconCircuitResistor,
    'alarm': IconAlarm,
    'fire-extinguisher': IconFireExtinguisher,
    'wash-machine': IconWashMachine,
    'wash': IconWash,
    'fridge': IconFridge,
    'microwave': IconMicrowave,
    'blender': IconBlender,
    'grill': IconGrill,
    'vacuum-cleaner': IconVacuumCleaner,
    'ironing': IconIroning,
    'cooker': IconCooker,
    'device-tv': IconDeviceTv,
    'spray': IconSpray,
    'bucket': IconBucket,
    'trash': IconTrash,
    'hand-sanitizer': IconHandSanitizer,
    'wash-dryclean': IconWashDryclean,
    'bug': IconBug,
    'spider': IconSpider,
    'tools': IconTools,
    'tool': IconTool,
    'hammer': IconHammer,
    'hammer-drill': IconHammerDrill,
    'ruler-measure': IconRulerMeasure,
    'ladder': IconLadder,
    'crane': IconCrane,
    'wall': IconWall,
    'stairs': IconStairs,
    'door': IconDoor,
    'window': IconWindow,
    'fence': IconFence,
    'elevator': IconElevator,
    'building': IconBuilding,
    'building-warehouse': IconBuildingWarehouse,
    'brush': IconBrush,
    'paint': IconPaint,
    'paint-filled': IconPaintFilled,
    'plant': IconPlant,
    'plant-2': IconPlant2,
    'tree': IconTree,
    'trees': IconTrees,
    'flower': IconFlower,
    'shovel': IconShovel,
    'garden-cart': IconGardenCart,
    'lawn-mower': IconLawnMower,
    'home': IconHome,
    'home-2': IconHome2,
    'armchair': IconArmchair,
    'sofa': IconSofa,
    'bed': IconBed,
    'blind': IconBlind,
    'car': IconCar,
    'car-crane': IconCarCrane,
    'steering-wheel': IconSteeringWheel,
    'truck': IconTruck,
    'truck-delivery': IconTruckDelivery,
    'motorbike': IconMotorbike,
    'bike': IconBike,
    'engine': IconEngine,
    'gas-station': IconGasStation,
    'wifi': IconWifi,
    'router': IconRouter,
    'network': IconNetwork,
    'server': IconServer,
    'device-laptop': IconDeviceLaptop,
    'device-desktop': IconDeviceDesktop,
    'device-mobile': IconDeviceMobile,
    'antenna': IconAntenna,
    'satellite': IconSatellite,
    'device-cctv': IconDeviceCctv,
    'camera': IconCamera,
    'lock': IconLock,
    'key': IconKey,
    'shield-lock': IconShieldLock,
    'scissors': IconScissors,
    'shirt': IconShirt,
    'hanger': IconHanger,
    'massage': IconMassage,
    'yoga': IconYoga,
    'heartbeat': IconHeartbeat,
    'stethoscope': IconStethoscope,
    'first-aid-kit': IconFirstAidKit,
    'dog': IconDog,
    'cat': IconCat,
    'paw': IconPaw,
    'baby-carriage': IconBabyCarriage,
    'chef-hat': IconChefHat,
    'tools-kitchen': IconToolsKitchen,
    'tools-kitchen-2': IconToolsKitchen2,
    'cake': IconCake,
    'coffee': IconCoffee,
    'confetti': IconConfetti,
    'music': IconMusic,
    'microphone': IconMicrophone,
    'photo': IconPhoto,
    'video': IconVideo,
    'school': IconSchool,
    'book': IconBook,
    'package': IconPackage,
    'windmill': IconWindmill,
    'settings': IconSettings,
    'category': IconCategory,
};
