const colors = require('./src/theme/colors');

/**
 * Colours come from src/theme/colors.js, generated by scripts/sync-tokens.mjs
 * out of the console's own stylesheet. Do not hand-write colours here.
 *
 * @type {import('tailwindcss').Config}
 */
module.exports = {
    content: ['./src/**/*.{js,jsx,ts,tsx}'],
    presets: [require('nativewind/preset')],
    theme: {
        extend: {
            colors,
            // Mirrors the console, where every step derives from --radius: 0.5rem.
            borderRadius: {
                xs: '2px',
                sm: '4px',
                md: '6px',
                lg: '8px',
                xl: '10px',
                '2xl': '14px',
                '3xl': '22px',
            },
        },
    },
    plugins: [],
};
