const colors = require('./src/theme/colors');

/**
 * Colours come from src/theme/colors.js, generated by scripts/sync-tokens.mjs
 * out of the console's own stylesheet. Do not hand-write colours here.
 *
 * @type {import('tailwindcss').Config}
 */
module.exports = {
    content: ['./src/**/*.{js,jsx,ts,tsx}'],
    presets: [require('nativewind/preset')],
    darkMode: 'class',
    theme: {
        extend: {
            colors,
            // Matches the console's vite.config.ts. React Native has no
            // cascade, so these reach the app through ui/text.tsx and
            // ui/input.tsx rather than a body rule.
            fontFamily: {
                sans: ['Urbanist'],
                mono: ['JetBrains Mono'],
            },
            // Mirrors the console's --tracking-display. Negative tracking is
            // reserved for display sizes there, and a screen title is the
            // first one the app has.
            letterSpacing: {
                display: '-0.016em',
            },
            // Mirrors the console, where every step derives from --radius: 0.5rem.
            borderRadius: {
                xs: '2px',
                sm: '4px',
                md: '6px',
                lg: '8px',
                xl: '10px',
                '2xl': '14px',
                '3xl': '22px',
            },
        },
    },
    plugins: [],
};
