#!/usr/bin/env node
/**
 * Regenerate src/global.css from the console's design tokens.
 *
 * The server states its palette in oklch, which React Native cannot parse and
 * NativeWind only understands from v5. So the mobile palette is derived, not
 * authored: this converts every token to sRGB and writes the result. Run it
 * whenever resources/css/app.css changes; never hand-edit the output.
 *
 * Usage: node scripts/sync-tokens.mjs [path-to-app.css]
 */
import { readFileSync, writeFileSync } from 'node:fs';

const SOURCE = process.argv[2] ?? '../server/resources/css/app.css';
const CSS_OUTPUT = 'src/global.css';
const COLORS_OUTPUT = 'src/theme/colors.js';
const PALETTE_OUTPUT = 'src/theme/palette.js';

/** Tokens the app actually uses. Charts, sidebar, and grid are console-only. */
const WANTED = [
    'background', 'foreground', 'card', 'card-foreground', 'popover', 'popover-foreground',
    'primary', 'primary-foreground', 'secondary', 'secondary-foreground',
    'muted', 'muted-foreground', 'accent', 'accent-foreground',
    'destructive', 'destructive-foreground', 'destructive-subtle',
    'border', 'input', 'ring',
    'brand', 'brand-foreground', 'brand-subtle',
    'success', 'success-foreground', 'success-subtle',
    'warning', 'warning-foreground', 'warning-subtle',
    'info', 'info-foreground', 'info-subtle',
];

/** Convert one oklch triplet to sRGB channels, 0-255. */
function oklchToRgb(lightness, chroma, hueDegrees) {
    const hue = (hueDegrees * Math.PI) / 180;
    const a = chroma * Math.cos(hue);
    const b = chroma * Math.sin(hue);

    const l = (lightness + 0.3963377774 * a + 0.2158037573 * b) ** 3;
    const m = (lightness - 0.1055613458 * a - 0.0638541728 * b) ** 3;
    const s = (lightness - 0.0894841775 * a - 1.291485548 * b) ** 3;

    const linear = [
        4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
        -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
        -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
    ];

    return linear.map((channel) => {
        const encoded = channel <= 0.0031308
            ? 12.92 * channel
            : 1.055 * channel ** (1 / 2.4) - 0.055;

        return Math.max(0, Math.min(255, Math.round(encoded * 255)));
    });
}

/** Parse `oklch(L C H)` or `oklch(L C H / A%)`. */
function parseOklch(value) {
    const match = /^oklch\(\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)\s*(?:\/\s*([\d.]+)(%?)\s*)?\)$/.exec(value.trim());

    if (!match) {
        return null;
    }

    const [, lightness, chroma, hue, alpha, percent] = match;
    const [r, g, b] = oklchToRgb(Number(lightness), Number(chroma), Number(hue));

    if (alpha === undefined) {
        return { channels: `${r} ${g} ${b}` };
    }

    const opacity = percent ? Number(alpha) / 100 : Number(alpha);

    return { rgba: `rgba(${r}, ${g}, ${b}, ${Number(opacity.toFixed(3))})` };
}

/** Pull the declarations out of one CSS block. */
function tokensIn(css, selector) {
    const block = new RegExp(`${selector}\\s*\\{([\\s\\S]*?)\\n\\}`).exec(css);

    if (!block) {
        throw new Error(`Could not find ${selector} in ${SOURCE}`);
    }

    const tokens = {};

    for (const [, name, value] of block[1].matchAll(/--([\w-]+):\s*([^;]+);/g)) {
        const parsed = parseOklch(value);

        if (parsed && WANTED.includes(name)) {
            tokens[name] = parsed;
        }
    }

    return tokens;
}

function render(tokens, indent = '        ') {
    return WANTED
        .filter((name) => tokens[name])
        .map((name) => `${indent}--${name}: ${tokens[name].channels ?? tokens[name].rgba};`)
        .join('\n');
}

const css = readFileSync(SOURCE, 'utf8');
const light = tokensIn(css, ':root');
const dark = tokensIn(css, '\\.dark');

const missing = WANTED.filter((name) => !light[name]);

if (missing.length) {
    console.warn(`Not found in ${SOURCE}: ${missing.join(', ')}`);
}

writeFileSync(CSS_OUTPUT, `@tailwind base;
@tailwind components;
@tailwind utilities;

/*
 * GENERATED by scripts/sync-tokens.mjs from the console's resources/css/app.css.
 * Do not edit by hand -- rerun the script instead.
 *
 * The console states these in oklch. React Native cannot parse that, so they
 * are converted to sRGB here. Opaque tokens are space separated channels so
 * Tailwind's opacity modifiers keep working; tokens that carry their own alpha
 * are complete rgba() and are used as-is.
 */

@layer base {
    :root {
${render(light)}
    }

    .dark:root {
${render(dark)}
    }
}
`);

/*
 * Tailwind reads colours through the same variables. Opaque tokens go through
 * rgb() so the opacity modifiers (bg-primary/50) still resolve; the ones that
 * already carry alpha are passed straight through.
 */
const colors = WANTED.filter((name) => light[name]).map((name) => {
    const value = light[name].channels
        ? `rgb(var(--${name}) / <alpha-value>)`
        : `var(--${name})`;

    return `    '${name}': '${value}',`;
}).join('\n');

writeFileSync(COLORS_OUTPUT, `/*
 * GENERATED by scripts/sync-tokens.mjs. Do not edit by hand.
 */
module.exports = {
${colors}
};
`);

/**
 * The same tokens as literal colours, for the places a CSS variable cannot
 * reach. Opaque ones are hex because expo-splash-screen parses nothing else;
 * the ones carrying alpha keep their rgba() and are never asked for by it.
 */
function literals(tokens) {
    return WANTED
        .filter((name) => tokens[name])
        .map((name) => {
            const { channels, rgba } = tokens[name];
            const value = channels
                ? `#${channels.split(' ').map((channel) => Number(channel).toString(16).padStart(2, '0')).join('')}`
                : rgba;

            return `        '${name}': '${value}',`;
        })
        .join('\n');
}

/*
 * NativeWind resolves the variables for anything styled with a className. The
 * navigation theme and the splash screen are declared outside that, in plain
 * JavaScript and in app.config.ts, so they need the colours spelled out.
 */
writeFileSync(PALETTE_OUTPUT, `/*
 * GENERATED by scripts/sync-tokens.mjs. Do not edit by hand.
 */
module.exports = {
    light: {
${literals(light)}
    },
    dark: {
${literals(dark)}
    },
};
`);

console.log(`Wrote ${CSS_OUTPUT}, ${COLORS_OUTPUT} and ${PALETTE_OUTPUT}: ${Object.keys(light).length} light, ${Object.keys(dark).length} dark tokens.`);
