#!/usr/bin/env node
/**
 * Regenerate src/lib/logo.ts from the Paayo artwork.
 *
 * The path data is copied through untouched, so a new export from the designer
 * needs no conversion. What has to be computed is the view box: the mark is
 * drawn on a 1000x1000 canvas it does not fill, and a logo asked for at 56pt
 * should be 56pt of ink rather than 56pt of mostly padding. Measuring that by
 * hand is how a copy rots, which is why this is a script and not a comment.
 *
 * Usage: node scripts/sync-logo.mjs [path-to-svg]
 */
import { readFileSync, writeFileSync } from 'node:fs';

import { measure, readShapes } from './lib/svg-mark.mjs';

const SOURCE = process.argv[2] ?? 'assets/images/paayo-logo.svg';
const OUTPUT = 'src/lib/logo.ts';

const shapes = readShapes(readFileSync(SOURCE, 'utf8'));
const { left, top, width, height } = measure(shapes);

const literals = shapes
    .map(({ d, fill, translate }) =>
        `    { d: '${d}', fill: '${fill}', transform: 'translate(${translate[0]},${translate[1]})' },`)
    .join('\n');

writeFileSync(OUTPUT, `/*
 * GENERATED by scripts/sync-logo.mjs from ${SOURCE}. Do not edit by hand.
 */

/** The tight bounds of the ink, so a height asked for is a height drawn. */
export const LOGO_VIEW_BOX = '${left} ${top} ${width} ${height}';

/** How much narrower than tall the mark is, from those same bounds. */
export const LOGO_ASPECT = ${width} / ${height};

/** One filled path of the mark, painted in the order they are listed. */
export type LogoShape = { d: string; fill: string; transform: string };

/**
 * The mark carries its own colours rather than taking them from the palette.
 * It is one fixed thing in both themes: the white counter sits against the
 * green it is punched out of, never against the page, so it needs no dark
 * variant. See .ai/rules/logo.md before reaching for a token here.
 */
export const LOGO_SHAPES: LogoShape[] = [
${literals}
];
`);

console.log(`Wrote ${OUTPUT}: ${shapes.length} paths, view box ${left} ${top} ${width} ${height}.`);
