import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Generate src/lib/icons.ts from the console's curated icon list.
 *
 * Usage: node scripts/sync-icons.mjs [path-to-service-icons.json]
 */
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const source = process.argv[2] ?? resolve(root, '../server/resources/data/service-icons.json');
const target = resolve(root, 'src/lib/icons.ts');

const icons = JSON.parse(readFileSync(source, 'utf8'));

const imports = icons
    .map(({ component }) => `import ${component} from '@tabler/icons-react-native/${component}';`)
    .join('\n');

const entries = icons.map(({ name, component }) => `    '${name}': ${component},`).join('\n');

writeFileSync(
    target,
    `/*
 * GENERATED by scripts/sync-icons.mjs. Do not edit by hand.
 */

/*
 * Tabler exposes its per-icon subpaths through an exports map and no real
 * directory. Metro resolves it (unstable_enablePackageExports is on), so does
 * Jest, and types come from types/tabler-icons.d.ts -- only eslint-plugin-import's
 * resolver reads package.json "exports", which it does not.
 */
/* eslint-disable import/no-unresolved */
import type { Icon } from '@tabler/icons-react-native';

${imports}

/**
 * Every glyph a category may be drawn with, keyed by what the server stores.
 *
 * Imported one file at a time and never off the barrel: Metro does not shake,
 * and the barrel carries all 6184.
 */
export const ICONS: Record<string, Icon> = {
${entries}
};
`,
);

console.log(`wrote ${icons.length} icons to ${target}`);
